### PR TITLE
Images

### PR DESCRIPTION
**Pull request by joedunne-rit**
Image file added with two neutral character sprites for tutorial characters. file names are 'odin neutral' and 'sigrun neutral'. Tested to ensure sprites are properly sized to fit on screen.

### CODE REVIEW

**Comment by readylilian** [comment]
I believe we need a few more expressions for the tutorial, like for the bad end and good paths. I would implement those within this PR so we can have them all entered at once.

**Review by readylilian — CHANGES_REQUESTED** [review]
Requesting changes so it's more than just a comment, we need more expressions for the tutorial, at least an angry and a happy one, though I would recommend going through the storyline and @bsziklas script to ensure you're getting all of them in this pull request.

**Comment by joedunne-rit** [comment]
Made some character emotions that I felt fit the script that's currently written. If you need any specific emotions, for the tutorial or for any future work, let me know.

**Review by readylilian — APPROVED** [review]
Awesome! Thank you!

**Pull request merged**
