### PR TITLE
Day3

### PR DESCRIPTION
**Pull request by QwertyBobberson**

### CODE REVIEW

**Review by readylilian — CHANGES_REQUESTED** [review]
Please remove errors.txt, log.txt and traceback.txt from this commit.

Both non-default end-game situations rely on the Pope score being greater than 0, and since you've set the default score to 2, it always triggers a successful ending if you choose that route.   Setting this back to zero should fix that issue.

The pope doesn't have a happy sprite. In track one of reveal_pope, pope is never hidden (referenced as po). Following that you layer mab and odin right in front of each other. In track two, odin is also mis-refereced. You can't say the character's name to hide or show a sprite. It needs to be the specific sprite you want. This also shows with vampirechill and the other characters you used in this scene. 

Missing a lot of punctuation, please run through it again. to ensure you're nor missing periods etc.

**Review by bsziklas — COMMENTED** [review]
Missing punctuation on lines 1071 and 1091, other than that it looks good

**Review by readylilian — CHANGES_REQUESTED** [review]
Please check spelling/grammar, like guard is spelled wrong on line 1083. Other than that it seems fine 👍

**Review by joedunne-rit — APPROVED** [review]
Don't see anything other than what's already been stated, I have nothing to add.

**Review by readylilian — APPROVED** [review]
Thank you!

**Pull request merged**
