### PR TITLE
Act two day one dialogue

### PR DESCRIPTION
**Pull request by bsziklas**
added Act two day one dialogue

### CODE REVIEW

**Comment by bsziklas** [comment]
Some of the backgrounds didn't work, (probably because I put their names in wrong, but I can fix that)

**Review by readylilian — CHANGES_REQUESTED** [review]
- Please remove the errors.txt and log.txt from your commit.
- When you meet Ferrovax, you are using the out of date images. Depending on who merges first, either you or @joedunne-rit will need to adjust this in the script, same with besties
- All scenes need to be lowercase when called in code, ex HotelRoom.png would be hotelroom, and need to match the name's spelling, so vents->vent
Other than that, I went through all routes and everything else seems fine 👍

**Review by bsziklas — COMMENTED** [review]
Images, scenes, and files updated

**Review by readylilian — CHANGES_REQUESTED** [review]
Much better, but please remove errors.txt and log.txt

**Review by bsziklas — COMMENTED** [review]
Should be good now

**Review by QwertyBobberson — APPROVED** [review]

**Review by joedunne-rit — COMMENTED** [review]
Noticed something on line 420, it says `hide vampire sly`, and I'm assuming it's meant to be `hide vampirebad sly`

**Comment by bsziklas** [comment]
thank you, fixed that

**Review by readylilian — APPROVED** [review]
Thank you!

**Pull request merged**
